kind: Service
apiVersion: v1
metadata:
  name: {{.Values.service.name}} 
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{.Values.service.name}}
    visualize: "true" 
    hasHealthcheck: "{{ .Values.service.hasHealthcheck }}" 
spec:
  ports: 
    - port: 8080 
      name: "app"
      targetPort: 8080
    - port: 8081
      name: "admin"
      targetPort: 8081 
  selector: 
    app: {{ .Values.service.name }} 